### PR TITLE
[DO NOT MERGE] Add Segmentation Masks, GeoMx, RNAseq (with probes) and Xenium assay types 

### PR DESCRIPTION
**Pull request by shirey**
Add Segmentation Masks, GeoMx, RNAseq (with probes) and Xenium assay types to interim/dev assayclasses.json file.

### CODE REVIEW

**Comment by jpuerto-psc** [comment]
Thanks @yuanzhou - I think we were planning on just deleting this branch since these changes carried in to #147.

**Comment by AlanSimmons** [comment]
I think that we overcomplicated things. 
1. The change to the "dev server" was one file--the ontologies.json.
2. We wanted to make sure that the ontologies.json was identical to the changes to the response from the production assayclasses endpoint--i.e., that if you called assayclasses, you'd get the same content as what's in ontologies.json.

At this point, I think that we can resolve this by just manually copying the ontologies.json over to the hs-ontology-api dev branch.

We might want to consider moving the "dev server" thingy into its own repo.

**Comment by yuanzhou** [comment]
I agree with @AlanSimmons. Any future changes to the `dev/assayclasses.json` should be branched off the latest `main` then PR into `dev-integrate` rather than using `dev-integrate` as the base branch. This will prevent us from messing up the commit history of `main`.

**Comment by AlanSimmons** [comment]
Another option would be to move the files in the dev folder path into a separate repo, with the understanding that any PRs would merge only with dev-integrate. That would keep the static dev server separate from the hs-ontology-api. The dev server shares no files with hs-ontology-api, so it really shouldn't be in this repo, anyway.

**Comment by jpuerto-psc** [comment]
@AlanSimmons - feel free to discuss this w/ @shirey I have no opinion on where the code for this should live. Just need a server to hit against for testing

**Pull request closed without merging**
