### PR TITLE
Endpoints to support new assayclass model etc.

### PR DESCRIPTION
**Pull request by AlanSimmons**
So many things! But mostly, changes to support the new assayclass (aka, rule objects that model the testing_rule_chain.json).

This should be deployed in dev until the other HIVE teams get a chance to evaluate.

1. New assayclass endpoints - routes, controllers, query code to support new assayclass model in UBKG.
2. Deprecation of datasets endpoint.
3. Refactored legacy assayname and assaytype endpoints to account for new assay class model.
4. Refactored field-assay endpoint to account for new assay class model.
5. Fixes to organs endpoints to account for updates to UBERON codes for organs like left eye, left knee, etc. 
6. Updates to SmartAPI YAML

### CODE REVIEW

**Comment by yuanzhou** [comment]
@AlanSimmons ignore the VERSION conflict in this PR, and do NOT hit the "Resolve conflicts" button to try to resolve it. I'll take care of that when I merge the PR.

**Review by yuanzhou — CHANGES_REQUESTED** [review]
@AlanSimmons some of the issues I noticed from my testing:

1. `application_context=<value>` has been case-insensetive. Now it requires all UPPERCASED, should still be case-insensitive to allow some fault tolerance and also be compatible with the current usage.

2. `/assayclasses/<class-name>` returns an array, should it be just a single json object if there won't be multiple values?

3. `/assayclasses/<code>?application_context=HUBMAP` only takes the code `C200001` without the prefix, but the actual returned value uses prefix, e.g. ` "code": "HUBMAP:C200001"`. This can be confusing, and it's not a good design.

4. By deprecating the `/datasets` endpoint, we can't just remove it directly. We should still make it available and confirm there's no one still uses it BEFORE we can remove it. Looks like the SenNet team still uses it in a few places.

5. Entity-API uses `/valueset?parent_sab=HUBMAP&parent_code=C003041&child_sabs=HUBMAP` for `dataset_type` validation, need be careful because I've noticed it returns a few new values:

      - `Uknown`, in neo4j we use `UNKNOWN`
      - `CyCIF` is changed to `CycIF`, is this desired? Do we need to update pipeline?
      - We also need to verify other existing values and make Neo4j updates on existing data  if required.

6. A few minor things for the test scripts: 
    - The newly added `test_gateway.sh` is not executable, make it the same file permission as `test_api.sh`
    - `test_api.sh` gives me  "unbound variable" errors
    - `test_gateway.sh` gives me "UBKG_URL: unbound variable", also need to update the help instructions (it's the same as `test_api.sh`)
    - Use different test output files. 
    - Add `test.out` to .gitignore

**Comment by AlanSimmons** [comment]
Responses to preceding:
1. Corrected.
2. Done. 
3. Done. The `code` field is now split into `code` and `application_context`.
4. Per discussion and coordination with other stakeholders, we agreed that we would deprecate the legacy endpoint.
5. Open issue requiring coordination with PSC, CEDAR, DCWG. The UBKG models the testing rule chain. The CyCIF assay name has changed in UBKG.
6. All issues corrected.

**Review by yuanzhou — APPROVED** [review]
Will build on DEV against the latest `dev-integrate` branch of ubkg-api to test "New source_dictionary_url key/value in response to sources endpoint" altogether.

**Pull request merged**
