### PR TITLE
Scope of genes call set to UBKG; proposed endpoints for proteins and genes

### PR DESCRIPTION
**Pull request by AlanSimmons**
1. With the removal of calls to data from Cells API, the genes endpoint now has scope of UBKG--i.e., it returns all genes in UBKG, not just those relevant to HuBMAP.
2. The SmartAPI specification YAML describes proposed endpoints for:
- proteins
- protein/{id}
- celltypes
- celltype/{id}

### CODE REVIEW

**Comment by yuanzhou** [comment]
Updated change log:

- Refactored routes and controllers to genes-info and genes
- Repackaged pagination information into a Pagination class.
- Refactored for locations of utility scripts, such as neo4j_logic.py and cellsclient.py
- Updated YAML for new pagination object.
- Updated test script.

**Review by yuanzhou — CHANGES_REQUESTED** [review]
@AlanSimmons two things to change:

1. since you use underscore-separated fields (`approved_name`, `approved_symbol `...) in the response json payload, we should also do the same with the pagination fields for consistency. Add underscore as a separator for the following fields:
```
    "itemcount": 43143,
    "itemsperpage": 10,
    "startswith": "",
    "totalpages": 4315
```

2. To merge this PR, we'll also need to resolve the merge conflicts caused by `hs-ontology-api-spec.yaml`.

**Comment by AlanSimmons** [comment]
I changed all references everywhere (parameters, returns, etc.) to use underscores--e.g., starts_with instead of startswith.

**Comment by AlanSimmons** [comment]
Merge conflicts resolved in YAML file.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
